server:
  port: 8082
  context-path: /redis

spring:
  application:
    name: redis-demo
  datasource:
    url: jdbc:mysql://localhost:13306/yummy_mochi?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: t3Q8t5KWYJCCpJw
    main:
      allow-bean-definition-overriding: true
    redis:
      host: localhost
      port: 6379
      password:
    cache:
      type: redis

redisson:
    address: "redis://localhost:6379"