server:
  port: 8082
  servlet:
    context-path: /redis

spring:
  application:
    name: redis-demo
  datasource:
    main:
      allow-bean-definition-overriding: true
    redis:
      host: localhost
      port: 6379
      password:
    cache:
      type: redis

redisson:
    address: "redis://localhost:6379"